Feat app 216
buzzn/mybuzzn-backend pull request #88
Opened 2020-04-09 07:36 UTC by KatharinaGrett

2020-04-09 10:21 UTC, missgreenwood requested changes
Very good! Please integrate the suggested changes and get back to @clemensmanert or myself if you have any questions regarding the deployment process. Nicely done! :+1:

2020-04-09 10:21 UTC, missgreenwood commented on README.md
>  [loggers]
Please go over the whole README file and check the headline sizes. "Logging" should not be a sub-chapter of "How to deploy". Likewise, "Upgrading to a new version" cannot be a sub-chapter of "Logging" or "How to deploy". If you make any changes to the README, please do always check the rendered version to make sure everything is displayed proplerly. You can use a markdown renderer like https://dillinger.io/ to check your markdown changes.

2020-04-09 10:21 UTC, missgreenwood commented on README.md
> +| per capita consumption / pcc| Defined as consumption divided by inhabitants in kWh|
:+1:

2020-04-09 10:21 UTC, missgreenwood commented on migrations/versions/67a4de7f7cf1_.py
> +        old_table.alter_column('per_capita_consumption_cumulated', new_column_name='pkv_cumulated')
Just a comment to the whole alter table process: Please make sure this is working on the staging server before you deploy it to production. If you have any questions on how to deploy and upgrade the database, please don't hesitate to ask @clemensmanert or myself.

2020-04-09 10:21 UTC, missgreenwood commented on models/pcc.py
> +    """ Represents a user's per capita consumption in the backend. """
:+1:

2020-04-09 10:21 UTC, missgreenwood commented on models/pcc.py
>  from util.database import db
Consider using a more telling name like "per_capita_consumption" for the module instead of using another abbreviation.

2020-04-09 10:21 UTC, missgreenwood commented on routes/per_capita_consumption.py
> +from models.pcc import PerCapitaConsumption
See above, please consider using a more telling name for the module instead of another abbreviation.

2020-04-09 10:21 UTC, missgreenwood commented on routes/per_capita_consumption.py
> +ShowPerCapitaConsumption = Blueprint('ShowPerCapitaConsumption', __name__)
I'm not really happy with the naming here. I understand why you need to differentiate between Blueprint and column name, but what about an underscore for instance? "ShowPerCapitaConsumption" would be more of a function name than a route name, especially if you compare it to the other routes.

2020-04-09 10:21 UTC, missgreenwood commented on routes/per_capita_consumption.py
> +ShowPerCapitaConsumption = Blueprint('ShowPerCapitaConsumption', __name__)
If you are not familiar with the Python visibility concept and underscore conventions, you might take a look at this: https://dbader.org/blog/meaning-of-underscores-in-python

2020-04-09 10:21 UTC, missgreenwood commented on routes/per_capita_consumption.py
> +@ShowPerCapitaConsumption.route('/per-capita-consumption', methods=['GET'])
See above - there is no harm in leaving the route name as it is, but changing the Blueprint name internally to a more telling one.

2020-04-09 10:21 UTC, missgreenwood commented on setup_app.py
> +from routes.per_capita_consumption import ShowPerCapitaConsumption
See above.

2020-04-09 10:21 UTC, missgreenwood commented on setup_app.py
> +    from models.pcc import PerCapitaConsumption
See above.

2020-04-09 10:21 UTC, missgreenwood commented on setup_app.py
> +    app.register_blueprint(ShowPerCapitaConsumption)
See above.

2020-04-09 10:21 UTC, missgreenwood commented on tests/test_per_capita_consumption.py
> +from models.pcc import PerCapitaConsumption
See above.

2020-04-09 10:21 UTC, missgreenwood commented on tests/test_per_capita_consumption.py
> +    """ Unit tests for per capita consumption route and functions(). """
Please remove the brackets after "functions", I must have inserted them accidentally.

2020-04-09 10:21 UTC, missgreenwood commented on tests/test_per_capita_consumption_calculation.py
> +from models.pcc import PerCapitaConsumption
See above.

2020-04-09 10:21 UTC, missgreenwood commented on util/per_capita_consumption_calculation.py
> +from models.pcc import PerCapitaConsumption
See above.

2020-04-09 10:21 UTC, missgreenwood commented on util/per_capita_consumption_calculation.py
> +    :returns: the per_capita_consumption values for the given meter id and date or None if there is
Please remove the underscores from the textual description.

2020-04-09 10:21 UTC, missgreenwood commented on util/task.py
> +from models.pcc import PerCapitaConsumption
See above.

2020-04-09 10:21 UTC, missgreenwood commented on util/task.py
> +    Otherwise, write yesterday's per_capita_consumption for all users to the SQLite database.
See above, please remove the underscores from the textual description.

2020-04-09 10:21 UTC, missgreenwood commented on util/task.py
> +    """ Write the per_capita_consumption for each user to the SQLite database.
See above.

2020-04-16 12:23 UTC, clemensmanert commented on routes/per_capita_consumption.py
> +_PerCapitaConsumption = Blueprint('_PerCapitaConsumption', __name__)
Just out of curiosity: Why the leading underscore?

2020-04-17 08:45 UTC, merged